# 04_numpy

- numpy는 배열을 만드는데 도움을 주는 패키지
- 파이썬은 배열이 없으므로 numpy라는 외부 패키지를 이용하여 배열을 만듭니다.
- array(배열)은 list(리스트)와 비슷하지만 차이점이 존재합니다.
  - 배열은 원소의 자료형이 모두 동일합니다.
  - 배열은 원소의 갯수의 변경이 불가능합니다.
- list에 비하여 속도가 빠릅니다.
- list는 메모리를 많이 차지합니다.

In [3]:
import numpy as np # numpy를 np로 줄여 사용함

In [4]:
# 배열만들기
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
type(np.array([1, 2, 3, 4]))

numpy.ndarray

In [6]:
np.arange(10) # 0 ~ 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1, 10) # 1 ~ 9

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 리스트와의 차이

In [9]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [10]:
b = [1, 2, 3, 4]
b

[1, 2, 3, 4]

In [11]:
# 리스트에서 모든 방에 + 1 하는 연산
for i in b:
    print(i + 1)

2
3
4
5


In [13]:
# 배열에서 모든 방에 + 1 하는 연산
print(a + 1)
print(a * 2)
print(a - 1)

[2 3 4 5]
[2 4 6 8]
[0 1 2 3]


In [20]:
# 실습하기. a의 0번 방을 출력하세요
print(a[0])

# a의 0번부터 2번째 방전까지 출력하기
print(type(a[0:2]))

# a의 0번, 3번째 방을 출력하기
print(a[[0,3]])

1
<class 'numpy.ndarray'>
[1 4]


In [24]:
# 실습하기. a의 값이 짝수인 방만 출력하기
a % 2 == 0

array([False,  True, False,  True])

In [27]:
a[a % 2 == 0]

array([2, 4])

In [29]:
# 모양 확인하기
a.shape # 4행

(4,)

In [30]:
[[1, 2, 3], [4, 5, 6]]

[[1, 2, 3], [4, 5, 6]]

In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
a.shape # 2행 3열

[[1 2 3]
 [4 5 6]]


(2, 3)

In [38]:
# 리사이징
a.shape = (3, 2) # 2행 3열에서 3행 2열로 바꿈
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [42]:
# 실습하기. a에서 5보다 큰 데이터만 조회해주세요
a = np.arange(10)
a

a[a > 5]

array([6, 7, 8, 9])

In [45]:
# 다차원 배열
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# a의 0번 행의 0열을 조회하기
# - a[행, 열]
a[0, 0]

1

In [50]:
# a의 모든 행의 1열을 조회하기
a[:, 1]

array([2, 5])