# 13_scikit

In [ ]:
import pandas as pd
import numpy as np
from sklearn import datasets

### 데이터 정리 및 이해

In [ ]:
iris_dataset = datasets.load_iris()
iris_dataset

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [ ]:
iris_dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
# 실제데이터로부터 학습데이터(75%)와 테스트데이터(25%) 분리하기
from sklearn.model_selection import train_test_split

In [ ]:
# 예측을 할 데이터
iris_dataset.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
# 데이터에 따른 정답값
iris_dataset.target[0]

0

In [ ]:
# 정답값의 이름
iris_dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

```
- x_train = 학습용 데이터
- x_test = 테스트용 데이터
- y_train = 학습용 정답
- y_test = 테스트용 정답
```

In [ ]:
# 데이터 분리하기
x_train, x_test, y_train, y_test = train_test_split(iris_dataset.data, iris_dataset.target)

In [ ]:
# 우리가 만드는 머신러닝 알고리즘
class koreaML():
  # 데이터로부터 패턴을 발견
  def fit(self, x_train, y_train):
    print("우리는 의미가 없습니다.")

  # 패턴을 통한 예측
  def predict(self, x_test):
    predic = []
    for x in x_test:
      predic.append(1)
    return predic

### **모델학습**

In [ ]:
# 모델 학습하기
model = koreaML()

# 데이터에서 패턴발견하기
model.fit(x_train, y_train)

# 예측
prediction = model.predict(x_test)

우리는 의미가 없습니다.


In [ ]:
prediction == y_test

array([False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False, False, False,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True, False])

In [ ]:
np.mean(prediction == y_test)

0.47368421052631576

In [ ]:
# 최근접 이웃알고리즘으로 예측하기
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# 모델 학습하기
model = KNeighborsClassifier()

# 데이터에서 패턴발견하기
model.fit(x_train, y_train)

# 예측
prediction = model.predict(x_test)

In [ ]:
prediction == y_test

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
np.mean(prediction == y_test)

0.9736842105263158

In [ ]:
# 최근접 이웃알고리즘으로 예측하기
from sklearn import tree

In [ ]:
# 모델 학습하기
model = tree.DecisionTreeClassifier()

# 데이터에서 패턴발견하기
model.fit(x_train, y_train)

# 예측
prediction = model.predict(x_test)

In [ ]:
prediction == y_test

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [ ]:
np.mean(prediction == y_test)

0.9736842105263158